name: release addon

on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install scons markdown pre-commit uv
          sudo apt-get update -y
          sudo apt-get install -y gettext

      - name: Vendor add-on runtime dependencies
        run: |
          uv pip install --python 3.13 --target addon/lib64 --python-platform x86_64-pc-windows-msvc -r addon/requirements.txt
          uv pip install --python 3.13 --target addon/lib32 --python-platform i686-pc-windows-msvc   -r addon/requirements.txt

      - name: Build add-on
        run: scons . && scons pot

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: packaged_addon
          path: |
            ./*.nvda-addon
            ./*.pot

      - name: Append SHA256 to changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e "\nSHA256: " >> changelog.md
          sha256sum *.nvda-addon >> changelog.md

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.nvda-addon
            *.pot
          body_path: changelog.md
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref, '-') }}
